name: Scheduled Analysis and Documentation Update

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs weekly on Sundays at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      # This clones your repository into the runner.

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
      # Configures the desired Python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Upgrades pip and installs all packages listed in requirements.txt.

    - name: Run analysis script
      run: |
        python src/main.py
      # Runs the main analysis script. This downloads factor data (via our new scraper),
      # performs the market regime analysis, builds the portfolio, computes risk metrics,
      # and generates plots into the docs/_static directory.

    - name: Build Sphinx documentation
      working-directory: docs
      run: |
        make html
      # Changes into the docs folder and builds the HTML pages using Sphinx.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
      # This step deploys the built HTML documentation to the gh-pages branch.
      # GitHub Pages will then serve the site from this branch.